
const sectionStyles = {
    padding :'175px 25px',
};


const Education = () => {
    return ( 
        <section id="education" style={sectionStyles}>
            <h1>Education</h1>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan, ligula sit amet varius aliquet, urna arcu condimentum erat, non scelerisque ipsum libero nec erat. Ut eget bibendum velit. Nulla facilisi. Sed in ante vel est rhoncus vehicula. Maecenas aliquam mi at libero mollis, ac aliquet dui dapibus. Aliquam tempus diam at feugiat fringilla. Integer sed sapien vel nulla consectetur rutrum. Sed id diam quis libero suscipit accumsan. Nullam tincidunt diam vel velit fringilla, et mattis tortor faucibus. Fusce suscipit volutpat lorem, vel bibendum tortor finibus eu.

Vestibulum et nisl nec dolor pharetra lobortis. Nullam bibendum dapibus diam, a fringilla tellus interdum sed. Curabitur eu felis sed elit sollicitudin suscipit. Aliquam pretium dui sed mauris tristique, eget volutpat purus maximus. Mauris gravida erat id felis fringilla, vitae posuere libero vestibulum. Proin eu felis vitae turpis rhoncus iaculis nec sit amet sem. Maecenas pharetra posuere augue, nec malesuada eros molestie ac. Duis maximus hendrerit justo sed vestibulum. Aliquam erat volutpat. Nulla facilisi. Suspendisse potenti.

Praesent nec diam eu libero sollicitudin pharetra. Morbi tristique, ligula a consectetur elementum, odio elit interdum justo, in rutrum dolor leo eget lorem. Phasellus aliquam sapien nec lorem consequat, eget sagittis ligula convallis. Integer id eros varius, cursus odio sed, feugiat eros. Ut nec leo ac leo placerat sodales sit amet id lacus. Quisque in sodales ex. Pellentesque ut metus sed dui ultrices maximus. Curabitur at metus non libero maximus tristique ac eget nulla. Fusce nec est et sapien tincidunt volutpat. Nunc ornare luctus quam, nec fringilla odio condimentum ut. Integer non mauris vel felis egestas varius eget eget justo. Nullam nec fringilla orci. Ut nec est non felis mattis gravida ac in arcu.

Vivamus vestibulum sapien quis sem sodales blandit. Mauris faucibus velit in arcu elementum, et laoreet neque congue. Cras feugiat est non tortor faucibus, sit amet pellentesque purus vehicula. Nam ac libero ullamcorper, gravida tortor eu, posuere arcu.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan, ligula sit amet varius aliquet, urna arcu condimentum erat, non scelerisque ipsum libero nec erat. Ut eget bibendum velit. Nulla facilisi. Sed in ante vel est rhoncus vehicula. Maecenas aliquam mi at libero mollis, ac aliquet dui dapibus. Aliquam tempus diam at feugiat fringilla. Integer sed sapien vel nulla consectetur rutrum. Sed id diam quis libero suscipit accumsan. Nullam tincidunt diam vel velit fringilla, et mattis tortor faucibus. Fusce suscipit volutpat lorem, vel bibendum tortor finibus eu.

Vestibulum et nisl nec dolor pharetra lobortis. Nullam bibendum dapibus diam, a fringilla tellus interdum sed. Curabitur eu felis sed elit sollicitudin suscipit. Aliquam pretium dui sed mauris tristique, eget volutpat purus maximus. Mauris gravida erat id felis fringilla, vitae posuere libero vestibulum. Proin eu felis vitae turpis rhoncus iaculis nec sit amet sem. Maecenas pharetra posuere augue, nec malesuada eros molestie ac. Duis maximus hendrerit justo sed vestibulum. Aliquam erat volutpat. Nulla facilisi. Suspendisse potenti.

Praesent nec diam eu libero sollicitudin phar
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan, ligula sit amet varius aliquet, urna arcu condimentum erat, non scelerisque ipsum libero nec erat. Ut eget bibendum velit. Nulla facilisi. Sed in ante vel est rhoncus vehicula. Maecenas aliquam mi at libero mollis, ac aliquet dui dapibus. Aliquam tempus diam at feugiat fringilla. Integer sed sapien vel nulla consectetur rutrum. Sed id diam quis libero suscipit accumsan. Nullam tincidunt diam vel velit fringilla, et mattis tortor faucibus. Fusce suscipit volutpat lorem, vel bibendum tortor finibus eu.

Vestibulum et nisl nec dolor pharetra lobortis. Nullam bibendum dapibus diam, a fringilla tellus interdum sed. Curabitur eu felis sed elit sollicitudin suscipit. Aliquam pretium dui sed mauris tristique, eget volutpat purus maximus. Mauris gravida erat id felis fringilla, vitae posuere libero vestibulum. Proin eu felis vitae turpis rhoncus iaculis nec sit amet sem. Maecenas pharetra posuere augue, nec malesuada eros molestie ac. Duis maximus hendrerit justo sed vestibulum. Aliquam erat volutpat. Nulla facilisi. Suspendisse potenti.

Praesent nec diam eu libero sollicitudin pharetra. Morbi tristique, ligula a consectetur elementum, odio elit interdum justo, in rutrum dolor leo eget lorem. Phasellus aliquam sapien nec lorem consequat, eget sagittis ligula convallis. Integer id eros varius, cursus odio sed, feugiat eros. Ut nec leo ac leo placerat sodales sit amet id lacus. Quisque in sodales ex. Pellentesque ut metus sed dui ultrices maximus. Curabitur at metus non libero maximus tristique ac eget nulla. Fusce nec est et sapien tincidunt volutpat. Nunc ornare luctus quam, nec fringilla odio condimentum ut. Integer non mauris vel felis egestas varius eget eget justo. Nullam nec fringilla orci. Ut nec est non felis mattis gravida ac in arcu.

Vivamus vestibulum sapien quis sem sodales blandit. Mauris faucibus velit in arcu elementum, et laoreet neque congue. Cras feugiat est non tortor faucibus, sit amet pellentesque purus vehicula. Nam ac libero ullamcorper, gravida tortor eu, posuere arcu.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan, ligula sit amet varius aliquet, urna arcu condimentum erat, non scelerisque ipsum libero nec erat. Ut eget bibendum velit. Nulla facilisi. Sed in ante vel est rhoncus vehicula. Maecenas aliquam mi at libero mollis, ac aliquet dui dapibus. Aliquam tempus diam at feugiat fringilla. Integer sed sapien vel nulla consectetur rutrum. Sed id diam quis libero suscipit accumsan. Nullam tincidunt diam vel velit fringilla, et mattis tortor faucibus. Fusce suscipit volutpat lorem, vel bibendum tortor finibus eu.

Vestibulum et nisl nec dolor pharetra lobortis. Nullam bibendum dapibus diam, a fringilla tellus interdum sed. Curabitur eu felis sed elit sollicitudin suscipit. Aliquam pretium dui sed mauris tristique, eget volutpat purus maximus. Mauris gravida erat id felis fringilla, vitae posuere libero vestibulum. Proin eu felis vitae turpis rhoncus iaculis nec sit amet sem. Maecenas pharetra posuere augue, nec malesuada eros molestie ac. Duis maximus hendrerit justo sed vestibulum. Aliquam erat volutpat. Nulla facilisi. Suspendisse potenti.

Praesent nec diam eu libero sollicitudin phar
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan, ligula sit amet varius aliquet, urna arcu condimentum erat, non scelerisque ipsum libero nec erat. Ut eget bibendum velit. Nulla facilisi. Sed in ante vel est rhoncus vehicula. Maecenas aliquam mi at libero mollis, ac aliquet dui dapibus. Aliquam tempus diam at feugiat fringilla. Integer sed sapien vel nulla consectetur rutrum. Sed id diam quis libero suscipit accumsan. Nullam tincidunt diam vel velit fringilla, et mattis tortor faucibus. Fusce suscipit volutpat lorem, vel bibendum tortor finibus eu.

Vestibulum et nisl nec dolor pharetra lobortis. Nullam bibendum dapibus diam, a fringilla tellus interdum sed. Curabitur eu felis sed elit sollicitudin suscipit. Aliquam pretium dui sed mauris tristique, eget volutpat purus maximus. Mauris gravida erat id felis fringilla, vitae posuere libero vestibulum. Proin eu felis vitae turpis rhoncus iaculis nec sit amet sem. Maecenas pharetra posuere augue, nec malesuada eros molestie ac. Duis maximus hendrerit justo sed vestibulum. Aliquam erat volutpat. Nulla facilisi. Suspendisse potenti.

Praesent nec diam eu libero sollicitudin pharetra. Morbi tristique, ligula a consectetur elementum, odio elit interdum justo, in rutrum dolor leo eget lorem. Phasellus aliquam sapien nec lorem consequat, eget sagittis ligula convallis. Integer id eros varius, cursus odio sed, feugiat eros. Ut nec leo ac leo placerat sodales sit amet id lacus. Quisque in sodales ex. Pellentesque ut metus sed dui ultrices maximus. Curabitur at metus non libero maximus tristique ac eget nulla. Fusce nec est et sapien tincidunt volutpat. Nunc ornare luctus quam, nec fringilla odio condimentum ut. Integer non mauris vel felis egestas varius eget eget justo. Nullam nec fringilla orci. Ut nec est non felis mattis gravida ac in arcu.

Vivamus vestibulum sapien quis sem sodales blandit. Mauris faucibus velit in arcu elementum, et laoreet neque congue. Cras feugiat est non tortor faucibus, sit amet pellentesque purus vehicula. Nam ac libero ullamcorper, gravida tortor eu, posuere arcu.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan, ligula sit amet varius aliquet, urna arcu condimentum erat, non scelerisque ipsum libero nec erat. Ut eget bibendum velit. Nulla facilisi. Sed in ante vel est rhoncus vehicula. Maecenas aliquam mi at libero mollis, ac aliquet dui dapibus. Aliquam tempus diam at feugiat fringilla. Integer sed sapien vel nulla consectetur rutrum. Sed id diam quis libero suscipit accumsan. Nullam tincidunt diam vel velit fringilla, et mattis tortor faucibus. Fusce suscipit volutpat lorem, vel bibendum tortor finibus eu.

Vestibulum et nisl nec dolor pharetra lobortis. Nullam bibendum dapibus diam, a fringilla tellus interdum sed. Curabitur eu felis sed elit sollicitudin suscipit. Aliquam pretium dui sed mauris tristique, eget volutpat purus maximus. Mauris gravida erat id felis fringilla, vitae posuere libero vestibulum. Proin eu felis vitae turpis rhoncus iaculis nec sit amet sem. Maecenas pharetra posuere augue, nec malesuada eros molestie ac. Duis maximus hendrerit justo sed vestibulum. Aliquam erat volutpat. Nulla facilisi. Suspendisse potenti.

Praesent nec diam eu libero sollicitudin phar
        </section>
     );
}
 
export default Education;